<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use TCG\Voyager\Models\DataRow;
use TCG\Voyager\Models\DataType;
use TCG\Voyager\Models\Permission;

class TransactionsBreadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Create DataType for transactions
        $dataType = DataType::firstOrNew(['slug' => 'transactions']);
        $dataType->fill([
            'name' => 'transactions',
            'display_name_singular' => 'Transaction',
            'display_name_plural' => 'Transactions',
            'icon' => 'voyager-wallet',
            'model_name' => 'App\\Models\\Transaction',
            'controller' => 'App\\Http\\Controllers\\voyager\\TransactionController',
            'generate_permissions' => 1,
            'description' => 'Manage transactions with filters for customer, date, and duration.',
        ])->save();

        // Create DataRows for each field
        $dataRows = [
            [
                'data_type_id' => $dataType->id,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ],
            [
                'data_type_id' => $dataType->id,
                'field' => 'customer_id',
                'type' => 'number',
                'display_name' => 'Customer ID',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ],
            [
                'data_type_id' => $dataType->id,
                'field' => 'admin_id',
                'type' => 'number',
                'display_name' => 'Admin ID',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ],
            [
                'data_type_id' => $dataType->id,
                'field' => 'transaction_type',
                'type' => 'select_dropdown',
                'display_name' => 'Transaction Type',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => json_encode([
                    'options' => [
                        'deposit' => 'Deposit',
                        'withdraw_flour' => 'Withdraw Flour',
                        'withdraw_cash' => 'Withdraw Cash',
                        'grinding' => 'Grinding',
                        'balance_adjustment' => 'Balance Adjustment',
                    ],
                ]),
                'order' => 4,
            ],
            [
                'data_type_id' => $dataType->id,
                'field' => 'transaction_date',
                'type' => 'date',
                'display_name' => 'Transaction Date',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ],
            [
                'data_type_id' => $dataType->id,
                'field' => 'wheat_in_kg',
                'type' => 'number',
                'display_name' => 'Wheat In (KG)',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => json_encode(['step' => '0.01']),
                'order' => 6,
            ],
            [
                'data_type_id' => $dataType->id,
                'field' => 'wheat_out_kg',
                'type' => 'number',
                'display_name' => 'Wheat Out (KG)',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => json_encode(['step' => '0.01']),
                'order' => 7,
            ],
            [
                'data_type_id' => $dataType->id,
                'field' => 'grinding_charges_per_kg',
                'type' => 'number',
                'display_name' => 'Grinding Charges Per KG',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => json_encode(['step' => '0.01']),
                'order' => 8,
            ],
            [
                'data_type_id' => $dataType->id,
                'field' => 'grinding_total_charge',
                'type' => 'number',
                'display_name' => 'Grinding Total Charge',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => json_encode(['step' => '0.01']),
                'order' => 9,
            ],
            [
                'data_type_id' => $dataType->id,
                'field' => 'cash_in',
                'type' => 'number',
                'display_name' => 'Cash In',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => json_encode(['step' => '0.01']),
                'order' => 10,
            ],
            [
                'data_type_id' => $dataType->id,
                'field' => 'cash_out',
                'type' => 'number',
                'display_name' => 'Cash Out',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => json_encode(['step' => '0.01']),
                'order' => 11,
            ],
            [
                'data_type_id' => $dataType->id,
                'field' => 'balance_wheat_after',
                'type' => 'number',
                'display_name' => 'Balance Wheat After',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => json_encode(['step' => '0.01']),
                'order' => 12,
            ],
            [
                'data_type_id' => $dataType->id,
                'field' => 'balance_cash_after',
                'type' => 'number',
                'display_name' => 'Balance Cash After',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => json_encode(['step' => '0.01']),
                'order' => 13,
            ],
            [
                'data_type_id' => $dataType->id,
                'field' => 'weight_at_entry',
                'type' => 'number',
                'display_name' => 'Weight At Entry',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => json_encode(['step' => '0.01']),
                'order' => 14,
            ],
            [
                'data_type_id' => $dataType->id,
                'field' => 'weight_at_exit',
                'type' => 'number',
                'display_name' => 'Weight At Exit',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => json_encode(['step' => '0.01']),
                'order' => 15,
            ],
            [
                'data_type_id' => $dataType->id,
                'field' => 'card_tapped',
                'type' => 'checkbox',
                'display_name' => 'Card Tapped',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 16,
            ],
            [
                'data_type_id' => $dataType->id,
                'field' => 'remarks',
                'type' => 'text_area',
                'display_name' => 'Remarks',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 17,
            ],
            [
                'data_type_id' => $dataType->id,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 18,
            ],
            [
                'data_type_id' => $dataType->id,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 19,
            ],
        ];

        foreach ($dataRows as $dataRow) {
            DataRow::firstOrNew(['data_type_id' => $dataRow['data_type_id'], 'field' => $dataRow['field']])->fill($dataRow)->save();
        }

        // Generate permissions
        Permission::generateFor('transactions');
    }
}
